version: "3.9"

services:
  gve_devnet_ndfc_upgrade_scheduler:
    image: ghcr.io/gve-sw/gve_devnet_ndfc_upgrade_scheduler:latest
    container_name: gve_devnet_ndfc_upgrade_scheduler
    environment:
      # Note: Only API key OR user/pass are required
      - NDFC_API_KEY=
      - NDFC_USER=
      - NDFC_PASS=
      - NDFC_DOMAIN=
      - NDFC_HOST=
      - NDFC_DEBUG=False
    volumes:
      - config.yaml:/app/config.yaml
    restart: "no"
